name: Build And Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node?tab=readme-ov-file
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests
        run: npm run test:headless

      - name: Build and deploy dev
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npm run build:dev
          npm run deploy:dev

      - name: Build and deploy prod
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npm run build:prod
          npm run deploy:prod
