name: GitHub Pages

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node?tab=readme-ov-file
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Deploy # deployment to https://transparentdemocracy.github.io/website/ Github pages, in the gh-pages branch.
        uses: peaceiris/actions-gh-pages@v4 # https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#getting-started
        if: github.ref == 'refs/heads/main' && success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/website/browser
          enable_jekyll: true
          cname: watdoetdepolitiek.be # https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
